### ISSUE TITLE
Right click in Explorer hangs for long time

### ISSUE THREAD

**Issue by GoogleCodeExporter** [guberm/tortoisegit#1797]
```
What steps will reproduce the problem?
1. Open Explorer
2. Right click on any file/folder (not only git folders)
3. Explorer hangs (not responding) for 10 - 30 seconds.

What is the expected output? What do you see instead?
It should open context menu right away. Instead it opens it after 20+ seconds.

What version of TortoiseGit and msysgit are you using? On
what operating system?
TortoiseGit 1.8.3.0 
1.8.0.msysgit.0
Windows 8 64-bit.

Please provide any additional information below.
It started to be like that suddenly, just today. No Tortoise update, no system 
update.
When Explorer hangs CPU is not occupied, not explorer nor git is calculating 
then.
Disabling TortoiseGit shell extension solves the problem.

```

Original issue reported on code.google.com by `tweet...@gmail.com` on 27 May 2013 at 11:35
- Merged into: #1488

**Comment by futureweb** [comment]
Same Problem here ... right-clicking on a NFS mounted share on my Win 10 Workstation makes my Explorer hang for about 2-3 Minutes ...

**Comment by pianoboysai** [comment]
still exist in windows 10
version 2.13.3

**Comment by Chrispie** [comment]
Bump

**Comment by pianoboysai** [comment]
is there anyone is trying to solve this problem? come on, it is a big issue, I event want to uninstall it in windows 10

**Comment by singrcnz** [comment]
> Icon

Yeah. I tried changing "Status Cache" to "Shell" but it made no difference. Still takes 30s to right-click the first time I right-click (and, periodically, at other times).

(I also told it to exclude every drive on my system except the hard disk I'm working on, so there should be no issues from weird drives. It hasn't fixed the problem.)

**Comment by janwilmans** [comment]
Still happening on windows 10 with 2.8.0 ...

**Comment by Stiffner** [comment]
Same here
Windows 10 with 2.8.0 and still having the issue

**Comment by liupgd** [comment]
I suffered the same problem. But I resolved. I just removed the 'quick access' network folders. I think this is caused when explorer starts up. I guess the explorer(when installed with tortoisegit) will check some information of all 'quick access' folder shortcuts. But if you have some network folder  or invalid folder shortcuts in the 'quick access'. The explorer will hange there. I'm not sure whether the translation of 'quick access' is right, so I uploaded the screen shot below. Hope this will help all of you.
![image](https://user-images.githubusercontent.com/3350539/86198799-06f83700-bb8b-11ea-8242-a986bb28a9d9.png)

**Comment by mrhot05** [comment]
Hi had the exact problem like above. I solved it by removing a network folder from "quick access" area in Explorer.
I suggest to implement ignoring of quick access links to tortoiseGit shell extension.
Using:
Git-2.27.0-64-bit
TortoiseGit-2.10.0.2-64bit

**Comment by MNF** [comment]
May be fixed by https://gitlab.com/tortoisegit/tortoisegit/-/merge_requests/148.
Also may restrict settings to fixed drives only - see https://tortoisegit.org/docs/tortoisegit/tgit-dug-settings.html#tgit-dug-settings-overlay
